---
- name: "The service for the MySQL database"
  k8s:
    state: "{{ k8s_state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: wordpress-mysql
        namespace: "{{ k8s_ns }}"
        labels:
          app: wordpress
      spec:
        ports:
          - port: 3306
        selector:
          app: wordpress
          tier: mysql
        clusterIP: None

- name: "The local persistent volume for the MySQL database"
  k8s:
    state: "{{ k8s_state }}"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "mysql-persistent-storage-{{ site_id }}"
        namespace: "{{ k8s_ns }}"
        labels:
          type: local
      spec:
        storageClassName: local-storage
        capacity:
          storage: 8Gi
        accessModes:
          - ReadWriteOnce
        hostPath:
          path: "/mnt/data/pv{{ site_id }}/"

- name: "The persistent volume claim for the MySQL database"
  k8s:
    state: "{{ k8s_state }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mysql-pv-claim
        namespace: "{{ k8s_ns }}"
        labels:
          app: wordpress
      spec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi

- name: "The secret for accessing the database"
  k8s:
    state: "{{ k8s_state }}"
    definition:
      apiVersion: v1
      metadata:
        name: mysql-pass
        namespace: "{{ k8s_ns }}"
      data:
        password: bGV0bWVpbg==
      kind: Secret

- name: "The deployment for the MySQL database"
  k8s:
    state: "{{ k8s_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wordpress-mysql
        namespace: "{{ k8s_ns }}"
        labels:
          app: wordpress
      spec:
        selector:
          matchLabels:
            app: wordpress
            tier: mysql
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: wordpress
              tier: mysql
          spec:
            containers:
            - image: quay.io/yobasystems/alpine-mariadb:10.5.8-arm32v7
              name: mysql
              env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-pass
                    key: password
              ports:
              - containerPort: 3306
                name: mysql
              volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
            volumes:
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                claimName: mysql-pv-claim
